[build]
functions = "functions"
publish = "."
command = "npm install"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[functions]
node_bundler = "esbuild"
external_node_modules = ["@netlify/functions"]
directory = "functions"

[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"
Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
NODE_VERSION = "18"

[build.processing]
skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
port = 3998

[[redirects]]
from = "/callback"
to = "/index.html"
status = 200

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200